### PR TITLE
Sync promotion only specific to website/store.

### PR DESCRIPTION
**Pull request by joshirohit100**
While syncing the rules for a store/site, its syncing all rules even not applicable for the store/website.

### CODE REVIEW

**Comment by joshirohit100** [comment]
cc @sdelbosc

**Comment by sdelbosc** [comment]
@joshirohit100 looks good to me

**Comment by joshirohit100** [comment]
Now, this is available for review and merge.

**Comment by sdelbosc** [comment]
@malachy-mcconnell just in case it is not tracked we will need the same on V2

**Pull request merged**
